spring.application.name=music-player
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8081
spring.web.error.include-stacktrace=never
app.storage.location=storage/songs

spring.datasource.url=jdbc:postgresql://localhost:8000/music-player
spring.datasource.username=postgres
spring.datasource.password=1111

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.password=1111
