spring.application.name=music-player
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=${SERVER_PORT:8081}
spring.web.error.include-stacktrace=never
app.storage.location=${APP_STORAGE_LOCATION:storage/songs}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:8000/music-player}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1111}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:1111}

# Google OAuth2 Credentials loaded from .env (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT Security Configuration loaded from .env (JWT_SECRET, JWT_EXPIRATION)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}
